version: "3"
services:
  opencv:
    build: .
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./workspace:/workspace
      - .jupyter:/root/.jupyter
      - ~/tmp/.X11-unix:/tmp/.X11-unix:rw
    env_file:
      - .env

    command: jupyter lab --ip=0.0.0.0 --port=8000 --no-browser --allow-root
